name: petfinder
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.4.1+1

  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.6.4
  firebase_messaging: ^14.7.4
  flutterfire_ui: ^0.4.3+20
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.2
  lottie: ^3.3.1
  image_picker: ^1.0.7
  http: ^1.3.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/splash.json
    - assets/images/pet_login.png
    - assets/images/pet_signup.png
    - assets/images/start_image.png
