name: petfinder_flutterapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
  geolocator: ^14.0.0
  lottie: ^2.6.0
  image_picker: ^1.0.7
  geocoding: ^2.1.0

  flutter_facebook_auth: ^7.1.2
  flutter_svg: ^2.1.0
  google_sign_in: ^6.3.0
  intl: ^0.20.2
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Déplacé ici

# Configuration pour les icônes d'application
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo2.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/splash.json
    - assets/images/pet_login.png
    - assets/images/pet_signup.png
    - assets/images/start_image.png
    - assets/icons/
