name: petfinder_flutterapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  flutter_facebook_auth: ^7.1.2
  flutter_svg: ^2.1.0
  google_sign_in: ^6.3.0
  intl: ^0.20.2
  sign_in_with_apple: ^7.0.1
  google_maps_flutter: ^2.5.2
  lottie: ^3.3.1
  image_picker: ^1.0.4
  http: ^1.3.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/splash.json
    - assets/images/pet_login.png
    - assets/images/pet_signup.png
    - assets/images/start_image.png
