// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
///
///
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxgxuLcM-E9YPDFRCN3DBTE7ZlMD8AxMk',
    appId: '1:601100923346:web:98527f6ee8d189f098980b',
    messagingSenderId: '601100923346',
    projectId: 'petfinderapp-1172e',
    authDomain: 'petfinderapp-1172e.firebaseapp.com',
    storageBucket: 'petfinderapp-1172e.firebasestorage.app',
    measurementId: 'G-T8QE4W9GSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCylquH2GbTS2HZuXzBkPnKv0GcGD9LL9Y',
    appId: '1:601100923346:android:1fbdd43e97ccf00298980b',
    messagingSenderId: '601100923346',
    projectId: 'petfinderapp-1172e',
    storageBucket: 'petfinderapp-1172e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSEwy2yYaPT7SJG2es_9vMpt0QQERhREw',
    appId: '1:601100923346:ios:9369c6585b4ee03a98980b',
    messagingSenderId: '601100923346',
    projectId: 'petfinderapp-1172e',
    storageBucket: 'petfinderapp-1172e.firebasestorage.app',
    iosBundleId: 'com.example.petfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSEwy2yYaPT7SJG2es_9vMpt0QQERhREw',
    appId: '1:601100923346:ios:9369c6585b4ee03a98980b',
    messagingSenderId: '601100923346',
    projectId: 'petfinderapp-1172e',
    storageBucket: 'petfinderapp-1172e.firebasestorage.app',
    iosBundleId: 'com.example.petfinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxgxuLcM-E9YPDFRCN3DBTE7ZlMD8AxMk',
    appId: '1:601100923346:web:84d24a6689b1184f98980b',
    messagingSenderId: '601100923346',
    projectId: 'petfinderapp-1172e',
    authDomain: 'petfinderapp-1172e.firebaseapp.com',
    storageBucket: 'petfinderapp-1172e.firebasestorage.app',
    measurementId: 'G-MYP8W4J37E',
  );
}
